server {
    listen 443 ssl;
    server_name localhost;

    ssl_certificate /etc/nginx/ssl/server.crt;
    ssl_certificate_key /etc/nginx/ssl/server.key;

    root /var/www/public;
    index index.php index.html;

    # Handle Redirect
    location ^~ /mkcb/ {
    # Rewrite /mkcb/... /api/mkcb/... internally
        rewrite ^/mkcb/api/(.*)$ /api/mkcb/$1 break;

    # Directly route everything to index.php
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        include fastcgi_params;
        fastcgi_pass laravel_app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param PATH_INFO $fastcgi_path_info;
        fastcgi_param REQUEST_URI /api/mkcb/$1$is_args$args;
        fastcgi_index index.php;
    }

    # Laravel standard routing
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # PHP handling
    location ~ \.php$ {
        fastcgi_pass laravel_app:9000;  # adjust PHP version
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Optional: deny access to .env
    location ~ /\.env {
        deny all;
    }
}
